# Generated by Django 6.0.1 on 2026-02-03 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("cycle_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "steps",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "wellness_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("acne_level", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "fatigue_level",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "bloating_level",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "sleep_quality",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("mood", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"), name="unique_user_date"
                    )
                ],
            },
        ),
    ]
