# Generated by Django 6.0.1 on 2026-02-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailylog",
            name="water_glasses",
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
