# Generated by Django 6.0.1 on 2026-02-07 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_add_water_glasses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DietDayLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("early_morning", models.BooleanField(default=False)),
                ("breakfast", models.BooleanField(default=False)),
                ("mid_morning", models.BooleanField(default=False)),
                ("lunch", models.BooleanField(default=False)),
                ("evening_snack", models.BooleanField(default=False)),
                ("dinner", models.BooleanField(default=False)),
                ("bedtime", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_day_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"), name="unique_user_diet_date"
                    )
                ],
            },
        ),
    ]
