# Generated by Django 5.2.11 on 2026-02-09 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_add_diet_day_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "events_workshops",
                    models.BooleanField(
                        default=True, help_text="Events & Workshops notifications"
                    ),
                ),
                (
                    "health_tips",
                    models.BooleanField(
                        default=True, help_text="Health Tips notifications"
                    ),
                ),
                (
                    "app_updates",
                    models.BooleanField(
                        default=True, help_text="App Updates notifications"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification preference",
                "verbose_name_plural": "Notification preferences",
            },
        ),
    ]
