# Generated by Django 5.2.11 on 2026-02-09 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_add_notification_preference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="breakfast_reminder",
            field=models.BooleanField(
                default=True, help_text="Breakfast reminder (scheduled email)"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="daily_log_reminder",
            field=models.BooleanField(
                default=True,
                help_text="Daily log reminder – remind to enter today's log",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="stretch_reminder",
            field=models.BooleanField(
                default=True, help_text="Stretch reminder (scheduled email)"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="water_reminder",
            field=models.BooleanField(
                default=True, help_text="Water reminder (scheduled email)"
            ),
        ),
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("reminder_type", models.CharField(db_index=True, max_length=32)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date", "reminder_type"),
                        name="unique_user_date_reminder",
                    )
                ],
            },
        ),
    ]
