# Generated by Django 5.2.11 on 2026-02-11 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_add_reminder_preferences_and_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIDietPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "plan",
                    models.JSONField(
                        help_text='Full plan: { "day": str, "slots": [...] }'
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "checked",
                    models.JSONField(
                        default=list, help_text="List of bools, one per slot"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_diet_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI diet plan",
                "verbose_name_plural": "AI diet plans",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"), name="unique_user_ai_diet_date"
                    )
                ],
            },
        ),
    ]
