# Generated by Django 5.2.11 on 2026-02-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_add_ai_diet_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietdaylog",
            name="checked",
            field=models.JSONField(
                default=list, help_text="List of bools, one per slot"
            ),
        ),
        migrations.AddField(
            model_name="dietdaylog",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dietdaylog",
            name="plan",
            field=models.JSONField(
                blank=True,
                help_text='AI plan: { "day": str, "slots": [...] }',
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="AIDietPlan",
        ),
    ]
