# Generated by Django 5.2.11 on 2026-02-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_dietdaylog_add_plan_note_checked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dietdaylog",
            name="bedtime",
        ),
        migrations.RemoveField(
            model_name="dietdaylog",
            name="breakfast",
        ),
        migrations.RemoveField(
            model_name="dietdaylog",
            name="dinner",
        ),
        migrations.RemoveField(
            model_name="dietdaylog",
            name="early_morning",
        ),
        migrations.RemoveField(
            model_name="dietdaylog",
            name="evening_snack",
        ),
        migrations.RemoveField(
            model_name="dietdaylog",
            name="lunch",
        ),
        migrations.RemoveField(
            model_name="dietdaylog",
            name="mid_morning",
        ),
    ]
